<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Spatie\Permission\Models\Role as SpatieRole;

class Role extends SpatieRole
{

   /*  protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(function (Builder $builder) {
            $builder->where('roles.team_id', null);
        });
    }
 */
    /* public function branch()
    {
        return $this->belongsTo(Branch::class,'team_id');
    } */
}
